INSERT INTO cinemas(city) VALUES ('Warszawa');
INSERT INTO cinemas(city) VALUES ('Kraków');
INSERT INTO cinemas(city) VALUES ('Poznań');
INSERT INTO cinemas(city) VALUES ('Gdańsk');
INSERT INTO cinemas(city) VALUES ('Siedlce');

INSERT INTO movies(title) VALUES ('John Wick 4');
INSERT INTO movies(title) VALUES ('Skołowani');
INSERT INTO movies(title) VALUES ('Barbie');
INSERT INTO movies(title) VALUES ('Egzorcysta papieża');

INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (1, 1, 20, 20);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (2, 1, 20, 20);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (3, 1, 15, 15);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (4, 1, 18, 22);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (1, 2, 22, 22);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (2, 2, 20, 30);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (3, 2, 10, 10);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (1, 3, 10, 10);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (2, 3, 10, 10);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (3, 3, 10, 10);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (1, 4, 10, 10);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (2, 4, 10, 10);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (3, 4, 10, 10);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (4, 4, 10, 10);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (1, 5, 10, 10);
INSERT INTO auditoriums(number, cinema_id, seat_rows, seats_in_row) VALUES (2, 5, 10, 10);

INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 1, 1);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 2, 2);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 3, 3);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 4, 4);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 5, 1);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 6, 2);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 7, 3);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 8, 4);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 9, 1);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 10, 2);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 11, 3);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 12, 4);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 13, 1);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 14, 2);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 15, 2);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 16, 3);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 1, 3);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 2, 4);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 3, 1);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 4, 2);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 5, 3);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 6, 4);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 7, 1);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 8, 2);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 9, 3);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 10, 4);
INSERT INTO screenings(start_time, auditorium_id, movie_id) VALUES (CURRENT_TIMESTAMP, 11, 1);